name: Auto News Publisher

on:
  schedule:
    - cron: '0 * * * *'  # Hourly
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y libxml2-dev libxslt-dev
        
    - name: Run publishing pipeline
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_KEY }}
      run: |
        python scripts/news_bot.py
        python scripts/generate_homepage.py
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        
    - name: Validate Templates
      run: |
    if [ ! -f "templates/base.html" ]; then
      echo "::error::Missing template file!"
      exit 1
    fi
