name: Auto News Crawler

on:
  schedule:
    - cron: "0 */3 * * *"  # Setiap 3 jam
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run crawler
        run: python news_bot.py
