name: Auto News Crawler
on:
  schedule:
    - cron: '*/15 * * * *'  # Jalankan setiap jam
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python news_bot.py
      - name: Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add berita.json
          git commit -m "Auto-update berita [skip ci]"
          git push
