name: Auto News Crawler

on:
  workflow_dispatch:
  schedule:
  - cron: '*/5 * * * *'  # Setiap 15 menit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python news_bot.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add berita/
          git commit -m "📰 Update berita $(date +'%F %T')" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
